# Generated by Django 4.2.2 on 2023-08-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0002_hotel_remove_room_owned_by_room_is_reserved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realstate.hotel'),
        ),
    ]
