# Generated by Django 4.2.2 on 2023-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0003_alter_room_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
