# Generated by Django 4.2.2 on 2023-08-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0004_room_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_reserved',
        ),
    ]
